dist: focal
language: java
services: docker

install:
  - source .travis-ci/install-gpg.sh
  - source .travis-ci/install-zulu8.sh
  - source .travis-ci/install-maven.sh

script:
  - mvn -s settings.xml -U -V -Pgpg,release-sign-artifacts help:active-profiles clean install site site:stage
